import { useTheme, Text, Button, Grid, Tooltip, Modal, Textarea } from '@nextui-org/react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { theme } = useTheme();

  const title = "👋 Hello there!";
  const thumbUp = "👍";
  const thumbDown = "👎";

  const [visible, setVisible] = useState(false);

  const handleVote = (orientation: number) => {
    setVisible(true);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.button}>
          <ConnectButton />
        </div>

        <h1 className={styles.title}>
          {title}
        </h1>

        <p className={styles.description}>
          There is a battle between thumbs occuring on the Rinkeby testnet. Contribute to the battle by submitting a message and thumb!
        </p>

        <div>
          <Grid.Container gap={2} justify="center">
            <Grid>
              <Tooltip content={"Developers love Next.js"} rounded color="primary" placement='left'>
                <Button size="xl" shadow css={{ fontSize: "$xl5", background: '$colors$upGradient'}} onClick={() => handleVote(1)}>{thumbUp}</Button>
              </Tooltip>
            </Grid>
            <Grid>
              <Tooltip content={"Developers love Next.js"} rounded color="primary" placement='right'>
                <Button size="xl" shadow css={{ fontSize: "$xl5", background: '$colors$downGradient'}} onClick={() => handleVote(0)}>{thumbDown}</Button>
              </Tooltip>
            </Grid>
          </Grid.Container>
        </div>

        <Modal
          closeButton
          blur
          aria-labelledby='modal-title'
          open={visible}
          onClose={() => setVisible(false)}
        >
          <Modal.Header>
            <Text id="modal-title" size={18}>
              Finalize vote
            </Text>
          </Modal.Header>
          <Modal.Body>
            <Textarea placeholder="Please enter your message to be displayed on the blockchain here." />
          </Modal.Body>
          <Modal.Footer>
            <Button auto flat color="error" onClick={() => setVisible(false)}>
              Cancel
            </Button>
            <Button auto onClick={() => setVisible(false)}>
              Submit
            </Button>
          </Modal.Footer>
        </Modal>
      
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
